trigger:
- main

pool:
  name: classicagent-test

steps:

- checkout: self

- script: |
    echo "Code checked out successfully"
    dir
  displayName: 'Verify Source Code'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/website.zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'website'